apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pzxsdabg4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pzxsdabg4-java-springboot-gitops